### ISSUE TITLE
Cara akses string resources di mvp

### ISSUE THREAD

**Issue by qornanali** [alandwiprasetyo/Android-MVP#1]
Implementasi dulu contohnya seperti ini
`mContext.getString(R.String.text_login);`

Cara apa yang best practices untuk mengakses string resources di arsitektur mvp android?
Apakah dengan mengirimkan context melalui parameter constructornya presenter?

**Comment by programmermager** [comment]
bisa via param constructor, atau via param di method yang bersangkutan langsung gan.
